version: "3.7"

services:
    
    controller:
        build:
            context: .
            dockerfile: docker/Dockerfile.controller
        command: flask --app server run --debug --host=0.0.0.0 --port 5432
        volumes:
            - ./controller:/code
        ports:
            - "0.0.0.0:5432:5432"    

    worker:
        build:
            context: .
            dockerfile: docker/Dockerfile.worker
        user: "1000"
        privileged: true
        ulimits:
          rtprio: 99
          memlock: -1
        volumes:
            - /dev/snd:/dev/snd
            - /dev/shm:/dev/shm
            - ./go-webrtc-server:/build/go-webrtc-server/go-webrtc-server
            - ./client:/app/client
            - ./worker_startup.sh:/app/worker_startup.sh
            - ./controller/server.py:/app/server.py
            - ./controller/algoritme.py:/app/algoritme.py
            - ./AudioCollection:/audio
            #- ./log:/home/appuser/.sonic-pi/log/
        ports:
            - 8080:8080
            - 3033:3033
            - 3478:3478/udp
            - 3478:3478/tcp
            - 5349:5349/tcp
            - 54321:54321
        environment:
            - DEBIAN_FRONTEND=noninteractive
            #- PION_LOG_TRACE=all
